### ISSUE TITLE
Way to use warning-level insted silent option

### ISSUE THREAD

**Issue by edelciomolina** [leandrosimoes/ls-minifier#2]
Hi @leandrosimoes,
At Google Glosure Compiler there is the option `warningLevel` as described [here](https://github.com/google/closure-compiler-js#flags).

Is there a way that I can pass this option directly to the GCC if the `js-compressor` was defined, an example for use:
```shell
ls-minifier --input=./myfile.js 
            --js-compressor=gcc 
            --language-in=ECMASCRIPT_2018 
            --language-out=ECMASCRIPT5 
            --warning-level=QUIET
```

The importance here is that I want to ignore warnings when the compiling happens;
For example, I want to avoid warning messages like `unreachable code`
```js
const x = () => {
	return
	let a = 1
}
x()
```

**Comment by leandrosimoes** [comment]
@edelciomolina 

Just released the [2.1.0](https://www.npmjs.com/package/ls-minifier) version of this package with support for a `.ls-minifyrc` file to add some specifics configurations for each compressor. See the [docs](https://github.com/leandrosimoes/ls-minifier/releases/tag/v2.1.0) for more information.
