### ISSUE TITLE
Console.Err

### ISSUE THREAD

**Issue by edelciomolina** [leandrosimoes/ls-minifier#3]
Hi @leandrosimoes
Please, may you provide a way to the output from compiles be `console.err` instead of `console.log`

**Why this asking?**
We are using ls-minifier as part of a Github Workflow Action, so when we are using warningLevel=QUIET the output show only exceptions as expected, but is necessary that the output be an Error, for that the Github Actions cancelling the wrokflow when an exception happens.

https://github.com/leandrosimoes/ls-minifier/blob/7284fbe8f1d800b719d9db53b35d67d12a33a88a/index.js#L7

**Comment by leandrosimoes** [comment]
@edelciomolina Since you want to stop the process, I should `throw` the error and not just `console.error` it. So here is my implementation: https://github.com/leandrosimoes/ls-minifier/pull/4/files

Please, ​check if is everything good so I could merge it and release it.
